import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "@/components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <nav className="mx-auto max-w-6xl px-4 py-3 flex items-center gap-4">
            <a href="/" className="font-semibold">
              Notepad AI
            </a>
            <div className="flex items-center gap-3 text-sm">
              <a href="/search" className="underline-offset-4 hover:underline">
                Arama
              </a>
              <a href="/tags" className="underline-offset-4 hover:underline">
                Etiketler
              </a>
              <a
                href="/settings"
                className="underline-offset-4 hover:underline"
              >
                Ayarlar
              </a>
            </div>
            <div className="ml-auto flex items-center gap-2 text-sm">
              <ThemeToggle />
              <a href="/login" className="border rounded px-3 py-1">
                Giriş
              </a>
              <a
                href="/register"
                className="bg-black text-white rounded px-3 py-1"
              >
                Kayıt ol
              </a>
            </div>
          </nav>
        </header>
        <div className="mx-auto max-w-6xl px-4">{children}</div>
      </body>
    </html>
  );
}
